- name: Create function app with Ansible in Docker container
  hosts: localhost
  connection: local
  no_log: false
  vars_files:
   - ./vars-myvars.yml

  tasks:

    - name: Create an Azure App Service Plan
      azure.azcollection.azure_rm_appserviceplan:
        name: "{{ vm_name }}-appservice-plan"
        is_linux: true
        number_of_workers: 1
        resource_group: "{{ resource_group }}"
        sku: S1

    - name: Create a Storage Account for Azure Function
      azure.azcollection.azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name | lower }}2020func"
        kind: StorageV2
        account_type: Standard_LRS
        https_only: true
        tags:
          Tier: Development
          Venue: RedHatSummit
      register: output

    - name: Obtain Azure Container Registry Facts
      azure.azcollection.azure_rm_containerregistry_info:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}{{ rnum }}acr"
        retrieve_credentials: true
      register: acr_output

    - name: Create container based function app
      azure.azcollection.azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}functionapp"
        storage_account: "{{ vm_name | lower }}2020func"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}-appservice-plan"
        container_settings:
          name: functionapp
          registry_server_url: "{{ acr_output.registries[0].login_server }}"
          registry_server_user: "{{ acr_output.registries[0].name }}"
          registry_server_password: "{{ acr_output.registries[0].credentials.password }}"
